apiVersion: v1
kind: Service
metadata:
  name: k8-deployment-svc
  labels:
    app: k8-deployment
spec:
  selector:
    app: k8-deployment
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 31200
